export enum AUTH_REDUCER_ACTION {
  SET_USER_DATA = 'authReducer/SET_USER_DATA',
  GET_CAPTCHA_URL_SUCCESS = 'authReducer/GET_CAPTCHA_URL_SUCCESS',
  SET_PROFILE_SMALL_PHOTO = 'authReducer/SET_PROFILE_SMALL_PHOTO',
}
